### PR TITLE
Add option to limit the number of mp workers

### PR DESCRIPTION
**Pull request by ThadHouse**
Due to https://github.com/python/cpython/issues/89240, any use of mp.Pool with a number of workers greater than 60 fails. This means that by using cpu_count(), any system with more than 60 logical cores will crash when attempting to run.

Solve this by adding a flag to allow limiting the number of workers for users with systems with that many cores.

### CODE REVIEW

**Comment by BlankSpruce** [comment]
I appreciate the attempt. I've got two questions though:
- I acknowledge that due to that referred issue number of workers should be limited. Wouldn't it be enough to provide such limitation just in the code?
- Assuming that you have a good case for number of workers to manually tuned by the user, would it be ok with you if I introduced `-j/--jobs` flag similar to how tools like `make` and `ninja` do it?

**Comment by ThadHouse** [comment]
Limiting in code to a maximum of 60 would be fine. Thats actually what our project does. I just didn't know which you'd prefer. 

I'm fine with making the flags jobs instead of workers as well. Not set on any name. But I don't have any compelling reason not to just limit the number of runners and be done with it.

**Comment by BlankSpruce** [comment]
I prefer to not introduce new flags or options unless they accomplish something user might be interested in to have a concious choice. I'll research the topic further and probably today, as in CET zone, I'll release a new version with that change.

**Comment by ThadHouse** [comment]
@BlankSpruce it needs to be 60, not 61. You’re allowed 63 handles, and mp itself takes 3 of them.  61 will still fail.

**Comment by BlankSpruce** [comment]
Indeed, python bug tracker also mentions it here:
https://bugs.python.org/issue40263
as well as black's solution uses 60:
https://github.com/psf/black/blob/main/src/black/concurrency.py#L88

**Comment by BlankSpruce** [comment]
https://github.com/BlankSpruce/gersemi/releases/tag/0.11.0
Thank you and enjoy.

**Pull request merged**
